### ISSUE TITLE
consider using npm for js dependency management

### ISSUE THREAD

**Issue by rlskoeser** [mei-friend/mei-friend#70]
I noticed you have a package.json file under an npm directory, but it doesn't seem like you're using it (there was no mention in the installation instructions). I see you also have a bunch of js files and licenses in a deps module. I recommend installing these dependencies from npm where possible.

It looks like it is also possible to install CodeMirror components from npm instead of using a git submodule. An npm install is preferable to git submodule because it's a more standard setup and lets you easily specify the appropriate versions.

You may also want to consider webpack or vite for compiling and minimizing the js code, but that would be a secondary step building on npm install, and potentially a more complicated change to the mei-friend codebase. There are probably existing flask plugins that would help with this.

suggestion from JOSS review https://github.com/openjournals/joss-reviews/issues/6002

**Comment by musicog** [comment]
Thanks for this suggestion, and apologies for the late response. We've addressed this by:
* Including local copies of our dependencies (alongside licenses) in a new app/static/deps folder
* Adding CodeMirror as a submodule (rather than the suggested npm package) -- see below
* Using npm only to install the optional tests package (Playwright)

We chose to remain with the submodule rather than the npm dependency for CodeMirror because this removes npm entirely as a core requirement -- it is only necessary for Playwright installation.

We feel that the set-up now strikes a good balance between maintainability and usability (from the perspective of someone installing a local copy of mei-friend). It does mean that we will need to periodically check our dependencies for critical updates; we acknowledge this and will endeavour to do so regularly.
